version: '2.2'

services:
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    container_name: dev_bot_bank_api_checker
    entrypoint: python main.py
    env_file:
      - ./.de.env
    networks:
      - dev_bot_bank_api_checker_net

networks:
  dev_bot_bank_api_checker_net:
    driver: bridge